### ISSUE TITLE
i64-iadd should work once iconst.i64 is implemented

### ISSUE THREAD

**Issue by bjorn3** [bnjbvr/cranelift-x86#1]
It is legalized here:

https://github.com/CraneStation/cranelift/blob/2999076939f290de6dde6504fb91c6e9a6861355/cranelift-codegen/meta/src/shared/legalize.rs#L545

**Comment by bnjbvr** [comment]
It's not in the right legalization group (should be narrow). So either we'd need to copy it in the narrow group, or maybe we'd need to chain narrow with expand (latter doesn't quite make sense).

**Comment by bjorn3** [comment]
Oops that link refers to the `iadd_imm <out of range imm>` -> `iadd`. I mean:

https://github.com/CraneStation/cranelift/blob/2999076939f290de6dde6504fb91c6e9a6861355/cranelift-codegen/meta/src/shared/legalize.rs#L197

which is in the `narrow` group.

**Comment by bnjbvr** [comment]
That's right. In the example I tried, I was adding an iconst and another value; it happens that simple_preopt will replace iadd(iconst c, x) with iadd_imm(x, c). So either we need to not apply the simple_preopt if the ISA doesn't support it, or we need to undo it with legalization later.

**Comment by bnjbvr** [comment]
Now fixed and working!
